### ISSUE TITLE
New textures?

### ISSUE THREAD

**Issue by ghost** [tgame14/Advanced-Fluxian-Tools#1]
Its a great mod but the texture are fairly bland and in the case of the Laser Drill, downright ugly. If you don't feel like making new ones yourself I do plenty of work on Faithful 32 so I could make some for you.

**Comment by tgame14** [comment]
I Would love that ! I Am very bad at texturing :) Thanks for the suggestion, would definitely be something to play around with

**Comment by ghost** [comment]
![itemlaserdrill](https://cloud.githubusercontent.com/assets/1936130/2848550/8772c394-d0c0-11e3-81db-825b1d64ee56.png)
![entitylaserprojectile](https://cloud.githubusercontent.com/assets/1936130/2848551/8afcff20-d0c0-11e3-859c-5d1b3472705d.png)
![cellredstone](https://cloud.githubusercontent.com/assets/1936130/2848552/8dd4e910-d0c0-11e3-89e8-7d1485e1aef9.png)
![cellhardened](https://cloud.githubusercontent.com/assets/1936130/2848553/8df1eb0a-d0c0-11e3-90e0-0ce73a3b3625.png)
![cellleadstone](https://cloud.githubusercontent.com/assets/1936130/2848554/8df7f126-d0c0-11e3-917a-42ab430bbcee.png)

If you like them just let me know. I can see your mod being fairly popular so if you pick these I already made versions suitable for Faithful 32.

**Comment by tgame14** [comment]
That laser gun looks good, ill add it in to the repository, thanks a ton for the textures!
