### ISSUE TITLE
Make the chargepad a Multipart

### ISSUE THREAD

**Issue by philippTheCat** [tgame14/Advanced-Fluxian-Tools#12]

**Comment by philippTheCat** [comment]
(21:41:37) theCatsPaw: KingLemming: any advice on implementing microparts?
(21:41:44) KingLemming: yeah don't
(21:42:13) Drullkus: How so?
(21:42:22) KingLemming: updates happen out of order, race conditions
(21:42:34) KingLemming: chunkload issues, Tile entity cloning
(21:42:43) KingLemming: actually the tile entity cloning seems to be IC2

so, I'm not sure if this is actually a good idea, but I think it's worth a try

**Comment by tgame14** [comment]
I Was considering this, but to make it a multipart i need to either require FMP and add a lot of code, or add a whole lot of other code and have a soft dependency on FMP, which i would rather not, thanks nontheless for the suggestions!
