### ISSUE TITLE
Flux Laser Drill can destroy Bedrock from Thaumic Tinkerer.

### ISSUE THREAD

**Issue by Marti2203** [tgame14/Advanced-Fluxian-Tools#2]
Just tested the mod. Its cool, but it can break bedrock from Thaumic Tinkerer and It doubles the message for the Mode its on when changing the mode.
Example: 
"Laser Mode:Explosion"
"Laser Mode:Explosion"
"Laser Mode:Mine"
"Laser Mode:Mine"

**Comment by tgame14** [comment]
Ill add code to the bedrock thing, try and fix it, also will fix that double chat message
