### ISSUE TITLE
Bug with Chargers

### ISSUE THREAD

**Issue by Marti2203** [tgame14/Advanced-Fluxian-Tools#3]
I know this is the second issue i am writing. The block next to the charger becomes invisible and the charger is always dark. You can break the charger with hand and you don't get it back. I suggest you make it to be broken by an iron pickaxe or beyond. Sometimes my items aren't charged, even if they are in my hotbar.

**Comment by tgame14** [comment]
Can you give me a list of mods you run?

**Comment by Marti2203** [comment]
Its a big one. I tested it next to the energestic infuser and next to a block from big reactors. It makes every machine block, multiblock near it invisble and that creates the effect like the vanilla x-ray machine.

**Comment by tgame14** [comment]
Fixed, nearby blocks will render and charges inventory, increased hardness and resistence aswell
