### ISSUE TITLE
Add top tier charge pad?

### ISSUE THREAD

**Issue by ghost** [tgame14/Advanced-Fluxian-Tools#4]
There are technically 5 available sides which means a maximum input of 50000rf/t and with storage devices that hold a lot of power, that faster charging speed could be useful.

I actually already coded this in but I don't have a dev environment setup to compile this and I didn't want to submit an untested pull request.

**Comment by Marti2203** [comment]
This could be helpfull with using a wither generator from Extra Utillities, maybe it will add more possibillities to making a big power production line. 1 Question about the charge pads: can they charge items in an autonomous activator or a turtle. I haven't tested that.

**Comment by tgame14** [comment]
I Was considering this, but there are no Cables that can do 50,000 rf/t as im not sure how this would work nicely.. 

@Marti2203 no, those are blocks and cannot be charged that way, though i may very well add a block that can do that.

**Comment by ghost** [comment]
Energy transfer nodes from Extra Utilities can do 32000rf/t  and there are multiple sides to plug a cable in.

**Comment by tgame14** [comment]
i Will consider this, for now on hold

**Comment by tgame14** [comment]
I Have considered this and decided For, on the top tier of machinery there is a place for such an item, yet i am not sure how i will give it recipes and how much power it will hold, so i am closing the issue and putting this in the TODO list
