### ISSUE TITLE
ClassNotFoundException on CommonProxy

### ISSUE THREAD

**Issue by eiktyrner** [tgame14/Advanced-Fluxian-Tools#6]
Trying to run it on a SMP server using the TPPI pack (with some added mods) and get this crash on the CommonProxy not being found. 

http://pastebin.com/M6HYCxJs

**Comment by tgame14** [comment]
Whoops!

**Comment by eiktyrner** [comment]
Do you have a build server somewhere or a new release planned?
Why I'm asking is because I really want to try this mod but at the moment I can't without this fix. Maybe I should just learn how to build it from source and stop pestering you...

**Comment by tgame14** [comment]
I am setting up a build server, should be up by tommorow
